CREATE TABLE [dbo].[R_SKL_PGM] (
    [PGM_ID]               CHAR (6) NOT NULL,
    [DPTMNT_ID]            INT      NOT NULL,
    [SKL_ID]               CHAR (4) NOT NULL,
    [SKL_IS_REQUIRED]      BIT      DEFAULT ((0)) NOT NULL,
    [SKL_IS_COMPLEMENTARY] BIT      DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([PGM_ID] ASC, [DPTMNT_ID] ASC, [SKL_ID] ASC),
    CONSTRAINT [FK_R_SKL_PGM__PGM] FOREIGN KEY ([PGM_ID], [DPTMNT_ID]) REFERENCES [dbo].[TPGM] ([PGM_ID], [DPTMNT_ID]),
    CONSTRAINT [FK_R_SKL_PGM__SKL] FOREIGN KEY ([SKL_ID]) REFERENCES [dbo].[TSKL] ([SKL_ID])
);

