CREATE TABLE [dbo].[TCDTY] (
    [CD_TY]      CHAR (2)       NOT NULL,
    [CD_TY_DESC] NVARCHAR (250) NULL,
    [TRK_UID]    VARCHAR (7)    NULL,
    [RCD_CDTTM]  DATETIME       NULL,
    CONSTRAINT [PK_TCDTY] PRIMARY KEY CLUSTERED ([CD_TY] ASC)
);

