CREATE TABLE [dbo].[TEXAMSKLELEM] (
    [EXAM_ID]       INT            NOT NULL,
    [SKL_ID]        CHAR (4)       NOT NULL,
    [SKLELEM_SQNBR] TINYINT        NOT NULL,
    [RCD_CDTTM]     DATETIME       CONSTRAINT [DF_TEXAMSKLELEM_RCD_CDTTM] DEFAULT (getdate()) NULL,
    [SKLELEM_WGHT]  DECIMAL (5, 2) NULL,
    CONSTRAINT [PK_TEXAMSKLELEM] PRIMARY KEY CLUSTERED ([EXAM_ID] ASC, [SKL_ID] ASC, [SKLELEM_SQNBR] ASC),
    CONSTRAINT [FK_TEXAMSKLELEM_TEXAM] FOREIGN KEY ([EXAM_ID]) REFERENCES [dbo].[TEXAM] ([EXAM_ID]),
    CONSTRAINT [FK_TEXAMSKLELEM_TSKLELEM] FOREIGN KEY ([SKL_ID], [SKLELEM_SQNBR]) REFERENCES [dbo].[TSKLELEM] ([SKL_ID], [SKLELEM_SQNBR])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Association examen -- élément de compétence', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TEXAMSKLELEM';

