CREATE TABLE [dbo].[TROLE] (
    [ROLE_ID]   INT          NOT NULL,
    [ROLE_NM]   VARCHAR (50) NULL,
    [RCD_CDTTM] DATETIME     CONSTRAINT [DF_TROLE_RCD_CDTTM] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_TROLE] PRIMARY KEY CLUSTERED ([ROLE_ID] ASC)
);

