CREATE TABLE [dbo].[TSKLCNTXT] (
    [SKL_ID]      CHAR (4)       NOT NULL,
    [ID]          INT            IDENTITY (1, 1) NOT NULL,
    [IL_CONT_REL] NVARCHAR (MAX) NOT NULL,
    [RCD_CDTTM]   DATETIME       CONSTRAINT [DF_TSKLCNT_RCD_CDTTM] DEFAULT (getdate()) NULL,
    CONSTRAINT [FK_TCNTXT_TSKL] FOREIGN KEY ([SKL_ID]) REFERENCES [dbo].[TSKL] ([SKL_ID])
);

