CREATE TABLE [dbo].[TUSER] (
    [UID]       VARCHAR (7)   NOT NULL,
    [DPTMNT_ID] INT           NULL,
    [GVN_NM]    NVARCHAR (50) NULL,
    [SNM]       NVARCHAR (50) NULL,
    [RCD_CDTTM] DATETIME      CONSTRAINT [DF_TUSER_RCD_CDTTM] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_TUSER] PRIMARY KEY CLUSTERED ([UID] ASC),
    CONSTRAINT [FK_TUSER_TDPTMNT] FOREIGN KEY ([DPTMNT_ID]) REFERENCES [dbo].[TDPTMNT] ([DPTMNT_ID])
);

