CREATE TABLE [dbo].[TUSERAVL] (
    [UID]            VARCHAR (7) NOT NULL,
    [USER_AVL_SQNBR] INT         IDENTITY (1, 1) NOT NULL,
    [WEEKDAY_NBR]    INT         NOT NULL,
    [AVL_STM]        TIME (7)    NOT NULL,
    [AVL_NTM]        TIME (7)    NOT NULL,
    [RCD_CDTTM]      DATETIME    CONSTRAINT [DF_TUSERAVL_RCD_CDTTM] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_TUSERAVL] PRIMARY KEY CLUSTERED ([UID] ASC, [USER_AVL_SQNBR] ASC),
    CONSTRAINT [FK_TUSERAVL_TUSER] FOREIGN KEY ([UID]) REFERENCES [dbo].[TUSER] ([UID])
);

