CREATE TABLE [dbo].[TUSERROLE] (
    [UID]       VARCHAR (7) NOT NULL,
    [ROLE_ID]   INT         NOT NULL,
    [RCD_CDTTM] DATETIME    CONSTRAINT [DF_TUSERROLE_RCD_CDTTM] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_TUSERROLE] PRIMARY KEY CLUSTERED ([UID] ASC, [ROLE_ID] ASC),
    CONSTRAINT [FK_TUSERROLE_TROLE] FOREIGN KEY ([ROLE_ID]) REFERENCES [dbo].[TROLE] ([ROLE_ID]),
    CONSTRAINT [FK_TUSERROLE_TUSER] FOREIGN KEY ([UID]) REFERENCES [dbo].[TUSER] ([UID])
);

