CREATE DATABASE PCU001
GO

USE PCU001
GO


CREATE TABLE TCRS_TMPLT 
(
    CRS_ID NCHAR(10) NOT NULL,
    DPTMNT_ID INT NULL,
    CRS_TITLE NVARCHAR(50) NULL,
    UNITS DECIMAL(3,2) NULL,
    CRS_DESC NTEXT NULL,
    INTENT NTEXT NULL,
    DPTMT_APPRVL_DT DATETIME NULL,
    CMTE_APPRVL_DT DATETIME NULL,
    BOARD_APPROVL_DT DATETIME NULL,
    TRACKING_UID VARCHAR(7) NULL,
    RECORD_CDTTM DATETIME NULL
);


CREATE TABLE TSKL 
(
    SKL_ID NCHAR(4) NOT NULL,
    SKL_TITLE VARCHAR(200) NULL,
    ATTD NTEXT NULL,
    TRACKING_UID VARCHAR(7) NULL,
    RECORD_CDTTM DATETIME NULL
);


CREATE TABLE TSKLELEM 
(
    SKL_ID NCHAR(4) NOT NULL,
    SKL_ELEM_SQNBR SMALLINT NOT NULL,
    SKL_ELEM_TITLE NVARCHAR(50) NULL,
    SKL_ELEM_DESC NTEXT NULL,
    TRACKING_UID VARCHAR(7) NULL,
    RECORD_CDTTM DATETIME NULL
);


CREATE TABLE TSKLTMPLT 
(
    CRS_ID NCHAR(10) NOT NULL,
    SKL_ELEM_SQNBR SMALLINT NOT NULL,
    SKL_ID NCHAR(4) NOT NULL
);


ALTER TABLE TCRS_TMPLT 
  ADD CONSTRAINT TCRS_TMPLT_PK PRIMARY KEY (
    CRS_ID)
ALTER TABLE TSKL 
  ADD CONSTRAINT TSKL_PK PRIMARY KEY (
    SKL_ID)  ;
ALTER TABLE TSKLELEM 
  ADD CONSTRAINT TSKLELEM_PK PRIMARY KEY (
    SKL_ID, SKL_ELEM_SQNBR)  ;

ALTER TABLE TSKLELEM
  ADD CONSTRAINT TSKLELEM__TSKL_FK 
    FOREIGN KEY (SKL_ID)
      REFERENCES TSKL;

ALTER TABLE TSKLTMPLT
  ADD CONSTRAINT TSKLTMPLT_TCRS_TMPLT_FK 
    FOREIGN KEY (CRS_ID)
      REFERENCES TCRS_TMPLT;

ALTER TABLE TSKLTMPLT
  ADD CONSTRAINT TSKLTMPLT_TSKLELEM_FK 
    FOREIGN KEY (SKL_ID, SKL_ELEM_SQNBR)
      REFERENCES TSKLELEM;
